import { useEffect, useState } from "react";

import apiClient, { CanceledError } from "./services/api-client";

interface User {
  id: number;
  name: string;
}

function App() {
  const [users, setUsers] = useState<User[]>([]);
  const [error, setError] = useState("");
  useEffect(() => {
    const controller = new AbortController();
    apiClient
      .get<User[]>("users", {
        signal: controller.signal,
      })
      .then((res) => setUsers(res.data))
      .catch((err) => {
        if (err instanceof CanceledError) return;
        setError(err.message);
      });
    return () => controller.abort();
  }, []);

  function addUser() {
    const originalUsers = users;
    const user = { id: 0, name: "Vincent" };
    setUsers([user, ...users]);
    apiClient
      .post("users", user)
      // to get the id generated by the server
      .then(({ data: savedUser }) => setUsers([savedUser, ...users]))
      // .then((res) => setUsers([res.data, ...users]))
      .catch((err) => {
        setError(err.message);
        setUsers(originalUsers);
      });
  }

  function deleteUser(id: number) {
    const originalUsers = users;
    setUsers(users.filter((user) => user.id != id));

    apiClient.delete("users/" + id).catch((err) => {
      setError(err.message);
      setUsers(originalUsers);
    });
  }
  return (
    <>
      {error && <p className="text-danger">{error}</p>}
      <button className="btn btn-primary mb3" onClick={addUser}>
        Add
      </button>
      <ul className="list-group">
        {users.map((user) => (
          <li
            key={user.id}
            className="list-group-item d-flex justify-content-between"
          >
            {user.name}
            <button
              className="btn btn-outline-danger"
              onClick={() => deleteUser(user.id)}
            >
              Delete
            </button>
          </li>
        ))}
      </ul>
    </>
  );
}

export default App;
